on:
  pull_request:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
      - name: Install and Build
        run: |
          npm install
          ./node_modules/.bin/typedoc
